#!/usr/bin/env node
/**
 * Generate deploy/.env (gitignored + dockerignored) for the VPS backend, from the
 * local .env.local + .secrets/lab_api_key.txt. Prints only var NAMES, never values.
 * The VPS reads these at runtime (docker compose env_file). Re-run after rotating any key.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const env = {};
for (const l of readFileSync(join(ROOT, '.env.local'), 'utf8').split('\n')) {
  const t = l.trim(); if (!t || t.startsWith('#') || !t.includes('=')) continue;
  const i = t.indexOf('='); env[t.slice(0, i).trim()] = t.slice(i + 1).trim();
}
const labKey = readFileSync(join(ROOT, '.secrets/lab_api_key.txt'), 'utf8').trim();
const APP = env.ALGOLIA_APP_ID || '0EXRPAXB56';

// Vars the backend reads at runtime (grep-verified against lab/server/src).
const REQUIRED = [
  'ALGOLIA_ADMIN_API_KEY', 'ALGOLIA_PROVIDER_GEMINI_ID', 'ALGOLIA_AGENT_MODEL',
  'VITE_ALGOLIA_SEARCH_API_KEY', 'GOOGLE_API_KEY',
  'ALGOLIA_AGENT_P1_ID', 'ALGOLIA_AGENT_P3_ID',
  'ALGOLIA_AGENT_TECH_KEYWORD_ID', 'ALGOLIA_AGENT_TECH_NEURAL_ID',
  'ALGOLIA_AGENT_MARKETER_KEYWORD_ID', 'ALGOLIA_AGENT_MARKETER_NEURAL_ID',
  'ALGOLIA_AGENT_ACADEMY_KEYWORD_ID', 'ALGOLIA_AGENT_ACADEMY_NEURAL_ID',
  'ALGOLIA_AGENT_SUPPORT_KEYWORD_ID', 'ALGOLIA_AGENT_SUPPORT_NEURAL_ID',
];
const missing = REQUIRED.filter((k) => !env[k]);
if (missing.length) { console.error('MISSING in .env.local:', missing.join(', ')); process.exit(1); }
if (!labKey) { console.error('MISSING/empty .secrets/lab_api_key.txt'); process.exit(1); }

const lines = [
  '# Generated by build_deploy_env.mjs — DO NOT COMMIT. Mirrors .env.local server-side vars.',
  'PORT=8787', 'NODE_ENV=production', 'LLM_PROVIDER=gemini',
  `LAB_API_KEY=${labKey}`,
  `ALGOLIA_APP_ID=${APP}`, `VITE_ALGOLIA_APP_ID=${APP}`,
  ...REQUIRED.map((k) => `${k}=${env[k]}`),
];
writeFileSync(join(ROOT, 'deploy', '.env'), lines.join('\n') + '\n', { mode: 0o600 });
console.log('wrote deploy/.env (mode 600) with vars:', lines.filter((l) => l.includes('=') && !l.startsWith('#')).map((l) => l.split('=')[0]).join(', '));
